In [ ]:
import pandas as pd

# Data dummy untuk tabel city
data = {
    'city_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'city_name': ['Jakarta', 'Bandung', 'Surabaya', 'Semarang', 'Yogyakarta', 'Medan', 'Makassar', 'Palembang', 'Balikpapan', 'Denpasar'],
    'latitude': [-6.2088, -6.9175, -7.2575, -6.9932, -7.7956, 3.5952, -5.1477, -2.9761, -1.2675, -8.6500],
    'longitude': [106.8456, 107.6191, 112.7521, 110.4203, 110.3695, 98.6722, 119.4327, 104.7751, 116.8289, 115.2167]
}

# Membuat DataFrame dari data
df = pd.DataFrame(data)

# Menampilkan DataFrame
df

   city_id   city_name  latitude  longitude
0        1     Jakarta   -6.2088   106.8456
1        2     Bandung   -6.9175   107.6191
2        3    Surabaya   -7.2575   112.7521
3        4    Semarang   -6.9932   110.4203
4        5  Yogyakarta   -7.7956   110.3695
5        6       Medan    3.5952    98.6722
6        7    Makassar   -5.1477   119.4327
7        8   Palembang   -2.9761   104.7751
8        9  Balikpapan   -1.2675   116.8289
9       10    Denpasar   -8.6500   115.2167

In [ ]:
import pandas as pd
import random

# Data dummy untuk atribut city_id (mengacu pada tabel city)
city_id = [1, 2, 3, 4, 5, 6, 7, 8]
city_name = ['Jakarta', 'Bandung', 'Surabaya', 'Semarang', 'Yogyakarta', 'Medan', 'Makassar', 'Palembang']

# Data dummy untuk atribut lainnya
user_id = [i+1 for i in range(10)]
first_names = ['Adi', 'Budi', 'Citra', 'Dewi', 'Eka', 'Fajar', 'Gita', 'Hadi', 'Indra', 'Joko']
last_names = ['Wibowo', 'Susilo', 'Kusuma', 'Wijaya', 'Santoso', 'Purnomo', 'Pratama', 'Putra', 'Mulyono', 'Wijaya']
birth_dates = ['1990-01-01', '1992-03-15', '1988-05-20', '1995-07-10', '1985-09-05', '1998-11-12', '1993-02-25', '1987-04-30', '1991-08-18', '1989-12-03']
contact_nums = ['08123456789', '08234567890', '08345678901', '08456789012', '08567890123', '08678901234', '08789012345', '08890123456', '08901234567', '09012345678']
emails = [first.lower() + '.' + last.lower() + '@example.com' for first, last in zip(first_names, last_names)]
addresses = [str(random.randint(1, 100)) + ' ' + random.choice(['Jl. Sudirman', 'Jl. Gatot Subroto', 'Jl. Diponegoro']) for _ in range(10)]
city_ids = [random.choice(city_id) for _ in range(10)]

# Membuat DataFrame dari data
data = {
    'seller_id': user_id,
    'first_name': first_names,
    'last_name': last_names,
    'birth_date': birth_dates,
    'contact_num': contact_nums,
    'email': emails,
    'address': addresses,
    'city_id': city_ids
}
df = pd.DataFrame(data)

# Menampilkan DataFrame
df

,seller_id,first_name,last_name,birth_date,contact_num,email,address,city_id
0,1,Adi,Wibowo,1990-01-01,08123456789,adi.wibowo@example.com,79 Jl. Gatot Subroto,2
1,2,Budi,Susilo,1992-03-15,08234567890,budi.susilo@example.com,25 Jl. Diponegoro,3
2,3,Citra,Kusuma,1988-05-20,08345678901,citra.kusuma@example.com,48 Jl. Gatot Subroto,4
3,4,Dewi,Wijaya,1995-07-10,08456789012,dewi.wijaya@example.com,91 Jl. Diponegoro,6
4,5,Eka,Santoso,1985-09-05,08567890123,eka.santoso@example.com,73 Jl. Sudirman,1
5,6,Fajar,Purnomo,1998-11-12,08678901234,fajar.purnomo@example.com,79 Jl. Sudirman,8
6,7,Gita,Pratama,1993-02-25,08789012345,gita.pratama@example.com,64 Jl. Gatot Subroto,4
7,8,Hadi,Putra,1987-04-30,08890123456,hadi.putra@example.com,15 Jl. Diponegoro,8
8,9,Indra,Mulyono,1991-08-18,08901234567,indra.mulyono@example.com,27 Jl. Sudirman,8
9,10,Joko,Wijaya,1989-12-03,09012345678,joko.wijaya@example.com,25 Jl. Diponegoro,2

In [ ]:
import pandas as pd
import random

# Data dummy untuk nama depan dan nama belakang
first_names = ["Budi", "Ani", "Siti", "Joko", "Dewi", "Ahmad", "Rini", "Hadi", "Eka", "Wati"]
last_names = ["Santoso", "Wati", "Rahayu", "Kurniawan", "Purba", "Budi", "Susanto", "Hadi", "Sari", "Putra"]

# Data dummy untuk alamat
addresses = ["Jl. Merdeka No. 10", "Jl. Jenderal Sudirman No. 25", "Jl. Pahlawan No. 8", "Jl. Gajah Mada No. 15",
             "Jl. Diponegoro No. 30", "Jl. Imam Bonjol No. 12", "Jl. Ahmad Yani No. 5", "Jl. A. Yani No. 3",
             "Jl. Gatot Subroto No. 20", "Jl. Slamet Riyadi No. 7"]

# Generate data dummy
buyer_data = []
for i in range(10):
    first_name = random.choice(first_names)
    last_name = random.choice(last_names)
    email = f"{first_name.lower()}.{last_name.lower()}@example.com"
    address = random.choice(addresses)
    city_id = random.randint(1, 10)
    buyer_data.append({
        "buyer_id": i + 1,
        "first_name": first_name,
        "last_name": last_name,
        "birth_date": f"1990-01-01",
        "contact_num": f"08123456789{i}",
        "email": email,
        "address": address,
        "city_id": city_id
    })

# Buat DataFrame
df_buyer = pd.DataFrame(buyer_data)

# Tampilkan DataFrame
print("Data Dummy untuk Tabel Pembeli (Buyer):\n")
df_buyer

Data Dummy untuk Tabel Pembeli (Buyer):

,buyer_id,first_name,last_name,birth_date,contact_num,email,address,city_id
0,1,Rini,Hadi,1990-01-01,081234567890,rini.hadi@example.com,Jl. Ahmad Yani No. 5,5
1,2,Siti,Purba,1990-01-01,081234567891,siti.purba@example.com,Jl. Merdeka No. 10,9
2,3,Wati,Budi,1990-01-01,081234567892,wati.budi@example.com,Jl. Gatot Subroto No. 20,5
3,4,Hadi,Sari,1990-01-01,081234567893,hadi.sari@example.com,Jl. Gajah Mada No. 15,7
4,5,Hadi,Budi,1990-01-01,081234567894,hadi.budi@example.com,Jl. Gajah Mada No. 15,6
5,6,Siti,Kurniawan,1990-01-01,081234567895,siti.kurniawan@example.com,Jl. Slamet Riyadi No. 7,4
6,7,Hadi,Kurniawan,1990-01-01,081234567896,hadi.kurniawan@example.com,Jl. Diponegoro No. 30,3
7,8,Wati,Wati,1990-01-01,081234567897,wati.wati@example.com,Jl. Diponegoro No. 30,7
8,9,Hadi,Hadi,1990-01-01,081234567898,hadi.hadi@example.com,Jl. Ahmad Yani No. 5,2
9,10,Ani,Hadi,1990-01-01,081234567899,ani.hadi@example.com,Jl. Merdeka No. 10,6

In [ ]:
import pandas as pd

# Membuat data frame dengan data dummy
data = {
    'car_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'car_brand': ['Toyota', 'Honda', 'Nissan', 'Ford', 'Chevrolet', 'BMW', 'Mercedes-Benz', 'Audi', 'Hyundai', 'Kia'],
    'car_model': ['Camry', 'Civic', 'X-Trail', 'Focus', 'Cruze', '3 Series', 'C-Class', 'A4', 'Accent', 'Rio'],
    'car_type': ['Sedan', 'Sedan', 'SUV', 'Hatchback', 'Sedan', 'Sedan', 'SUV', 'Sedan', 'Hatchback', 'Hatchback'],
    'car_transmission': ['Automatic', 'Manual', 'Automatic', 'Manual', 'Automatic', 'Automatic', 'Automatic', 'Automatic', 'Manual', 'Automatic'],
    'year': [2015, 2018, 2017, 2019, 2016, 2020, 2018, 2017, 2016, 2019]
}

df = pd.DataFrame(data)

# Menampilkan data frame
df

   car_id      car_brand car_model   car_type car_transmission  year
0       1         Toyota     Camry      Sedan        Automatic  2015
1       2          Honda     Civic      Sedan           Manual  2018
2       3         Nissan   X-Trail        SUV        Automatic  2017
3       4           Ford     Focus  Hatchback           Manual  2019
4       5      Chevrolet     Cruze      Sedan        Automatic  2016
5       6            BMW  3 Series      Sedan        Automatic  2020
6       7  Mercedes-Benz   C-Class        SUV        Automatic  2018
7       8           Audi        A4      Sedan        Automatic  2017
8       9        Hyundai    Accent  Hatchback           Manual  2016
9      10            Kia       Rio  Hatchback        Automatic  2019

In [ ]:
import pandas as pd
from datetime import datetime

# Data dummy
car_data = {
    'car_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'car_brand': ['Toyota', 'Honda', 'Nissan', 'Ford', 'Chevrolet', 'BMW', 'Mercedes-Benz', 'Audi', 'Hyundai', 'Kia'],
    'car_model': ['Camry', 'Civic', 'X-Trail', 'Focus', 'Cruze', '3 Series', 'C-Class', 'A4', 'Accent', 'Rio'],
    'car_type': ['Sedan', 'Sedan', 'SUV', 'Hatchback', 'Sedan', 'Sedan', 'SUV', 'Sedan', 'Hatchback', 'Hatchback'],
    'car_transmission': ['Automatic', 'Manual', 'Automatic', 'Manual', 'Automatic', 'Automatic', 'Automatic', 'Automatic', 'Manual', 'Automatic'],
    'year': [2015, 2018, 2017, 2019, 2016, 2020, 2018, 2017, 2016, 2019]
}

user_data = {
    'user_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'first_name': ['Adi', 'Budi', 'Citra', 'Dewi', 'Eka', 'Fajar', 'Gita', 'Hadi', 'Indra', 'Joko'],
    'last_name': ['Wibowo', 'Susilo', 'Kusuma', 'Wijaya', 'Santoso', 'Purnomo', 'Pratama', 'Putra', 'Mulyono', 'Wijaya'],
    'birth_date': ['01/01/1990', '15/03/1992', '20/05/1988', '10/07/1995', '05/09/1985', '12/11/1998', '25/02/1993', '30/04/1987', '18/08/1991', '03/12/1989'],
    'contact_num': ['8123456789', '8234567890', '8345678901', '8456789012', '8567890123', '8678901234', '8789012345', '8890123456', '8901234567', '9012345678'],
    'email': ['adi.wibowo@example.com', 'budi.susilo@example.com', 'citra.kusuma@example.com', 'dewi.wijaya@example.com', 'eka.santoso@example.com', 'fajar.purnomo@example.com', 'gita.pratama@example.com', 'hadi.putra@example.com', 'indra.mulyono@example.com', 'joko.wijaya@example.com'],
    'address': ['15 Jl. Gatot Subroto', '89 Jl. Gatot Subroto', '55 Jl. Sudirman', '19 Jl. Diponegoro', '53 Jl. Diponegoro', '85 Jl. Gatot Subroto', '5 Jl. Gatot Subroto', '15 Jl. Sudirman', '67 Jl. Sudirman', '85 Jl. Gatot Subroto'],
    'city_id': [6, 5, 7, 4, 2, 5, 8, 2, 2, 6]
}

# Data untuk tabel iklan
advertisement_data = {
    'ads_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'title': ['Toyota Camry', 'Honda Civic', 'Nissan X-Trail', 'Ford Focus', 'Chevrolet Cruze',
              'BMW 3 Series', 'Mercedes-Benz C-Class', 'Audi A4', 'Hyundai Accent', 'Kia Rio'],
    'date_posted': [datetime(2022, 5, 1, 8, 30), datetime(2022, 5, 2, 10, 15), datetime(2022, 5, 3, 13, 45),
                    datetime(2022, 5, 4, 9, 20), datetime(2022, 5, 5, 11, 10), datetime(2022, 5, 6, 14, 0),
                    datetime(2022, 5, 7, 10, 30), datetime(2022, 5, 8, 12, 45), datetime(2022, 5, 9, 9, 0),
                    datetime(2022, 5, 10, 11, 30)],
    'odometer': [20000, 18000, 25000, 30000, 22000, 15000, 28000, 20000, 19000, 21000],
    'color': ['White', 'Black', 'Silver', 'Red', 'Blue', 'Gray', 'Green', 'Yellow', 'Orange', 'Purple'],
    'price': [250000000, 220000000, 280000000, 200000000, 240000000, 300000000, 270000000, 230000000, 210000000, 260000000],
    'user_id': user_data['user_id'],  # Menggunakan nilai yang sama dari tabel user_data
    'car_id': car_data['car_id']  # Menggunakan nilai yang sama dari tabel car_data
}

# Membuat DataFrame dari data iklan
advertisement_df = pd.DataFrame(advertisement_data)

# Menampilkan DataFrame
advertisement_df

,ads_id,title,date_posted,odometer,color,price,user_id,car_id
0,1,Toyota Camry,2022-05-01 08:30:00,20000,White,250000000,1,1
1,2,Honda Civic,2022-05-02 10:15:00,18000,Black,220000000,2,2
2,3,Nissan X-Trail,2022-05-03 13:45:00,25000,Silver,280000000,3,3
3,4,Ford Focus,2022-05-04 09:20:00,30000,Red,200000000,4,4
4,5,Chevrolet Cruze,2022-05-05 11:10:00,22000,Blue,240000000,5,5
5,6,BMW 3 Series,2022-05-06 14:00:00,15000,Gray,300000000,6,6
6,7,Mercedes-Benz C-Class,2022-05-07 10:30:00,28000,Green,270000000,7,7
7,8,Audi A4,2022-05-08 12:45:00,20000,Yellow,230000000,8,8
8,9,Hyundai Accent,2022-05-09 09:00:00,19000,Orange,210000000,9,9
9,10,Kia Rio,2022-05-10 11:30:00,21000,Purple,260000000,10,10

In [ ]:
import pandas as pd
from datetime import datetime

# Data dummy
car_data = {
    'car_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'car_brand': ['Toyota', 'Honda', 'Nissan', 'Ford', 'Chevrolet', 'BMW', 'Mercedes-Benz', 'Audi', 'Hyundai', 'Kia'],
    'car_model': ['Camry', 'Civic', 'X-Trail', 'Focus', 'Cruze', '3 Series', 'C-Class', 'A4', 'Accent', 'Rio'],
    'car_type': ['Sedan', 'Sedan', 'SUV', 'Hatchback', 'Sedan', 'Sedan', 'SUV', 'Sedan', 'Hatchback', 'Hatchback'],
    'car_transmission': ['Automatic', 'Manual', 'Automatic', 'Manual', 'Automatic', 'Automatic', 'Automatic', 'Automatic', 'Manual', 'Automatic'],
    'year': [2015, 2018, 2017, 2019, 2016, 2020, 2018, 2017, 2016, 2019]
}

user_data = {
    'user_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'first_name': ['Adi', 'Budi', 'Citra', 'Dewi', 'Eka', 'Fajar', 'Gita', 'Hadi', 'Indra', 'Joko'],
    'last_name': ['Wibowo', 'Susilo', 'Kusuma', 'Wijaya', 'Santoso', 'Purnomo', 'Pratama', 'Putra', 'Mulyono', 'Wijaya'],
    'birth_date': ['01/01/1990', '15/03/1992', '20/05/1988', '10/07/1995', '05/09/1985', '12/11/1998', '25/02/1993', '30/04/1987', '18/08/1991', '03/12/1989'],
    'contact_num': ['8123456789', '8234567890', '8345678901', '8456789012', '8567890123', '8678901234', '8789012345', '8890123456', '8901234567', '9012345678'],
    'email': ['adi.wibowo@example.com', 'budi.susilo@example.com', 'citra.kusuma@example.com', 'dewi.wijaya@example.com', 'eka.santoso@example.com', 'fajar.purnomo@example.com', 'gita.pratama@example.com', 'hadi.putra@example.com', 'indra.mulyono@example.com', 'joko.wijaya@example.com'],
    'address': ['15 Jl. Gatot Subroto', '89 Jl. Gatot Subroto', '55 Jl. Sudirman', '19 Jl. Diponegoro', '53 Jl. Diponegoro', '85 Jl. Gatot Subroto', '5 Jl. Gatot Subroto', '15 Jl. Sudirman', '67 Jl. Sudirman', '85 Jl. Gatot Subroto'],
    'city_id': [6, 5, 7, 4, 2, 5, 8, 2, 2, 6]
}

# Data untuk tabel iklan
advertisement_data = {
    'ads_id': range(1, 11),
    'title': [
        'Excellent Condition - Low Mileage',
        'Great Deal - Perfect for City Driving',
        'Sporty Look - Luxury Experience',
        'Elegant Style - Performance Redefined',
        'Budget Friendly - Compact and Efficient',
        'Excellent Condition - Low Mileage',
        'Great Deal - Perfect for City Driving',
        'Sporty Look - Luxury Experience',
        'Elegant Style - Performance Redefined',
        'Budget Friendly - Compact and Efficient'
    ],
    'date_posted': [
        datetime(2022, 5, 1, 8, 30), datetime(2022, 5, 2, 10, 15), datetime(2022, 5, 3, 13, 45),
        datetime(2022, 5, 4, 9, 20), datetime(2022, 5, 5, 11, 0), datetime(2022, 5, 6, 14, 30),
        datetime(2022, 5, 7, 8, 0), datetime(2022, 5, 8, 10, 45), datetime(2022, 5, 9, 13, 15),
        datetime(2022, 5, 10, 9, 30)
    ],
    'odometer': [50000, 40000, 30000, 20000, 10000, 45000, 35000, 25000, 15000, 5000],
    'color': ['Red', 'Blue', 'Black', 'White', 'Gray', 'Red', 'Blue', 'Black', 'White', 'Gray'],
    'price': [20000, 18000, 25000, 22000, 15000, 19000, 17000, 24000, 21000, 16000],
    'user_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'car_id': [1, 2, 3, 5, 6, 1, 2, 4, 4, 1]
}

# Menampilkan dalam bentuk tabel
advertisement_df = pd.DataFrame(advertisement_data)
advertisement_df

,ads_id,title,date_posted,odometer,color,price,user_id,car_id
0,1,Excellent Condition - Low Mileage,2022-05-01 08:30:00,50000,Red,20000,1,1
1,2,Great Deal - Perfect for City Driving,2022-05-02 10:15:00,40000,Blue,18000,2,2
2,3,Sporty Look - Luxury Experience,2022-05-03 13:45:00,30000,Black,25000,3,3
3,4,Elegant Style - Performance Redefined,2022-05-04 09:20:00,20000,White,22000,4,5
4,5,Budget Friendly - Compact and Efficient,2022-05-05 11:00:00,10000,Gray,15000,5,6
5,6,Excellent Condition - Low Mileage,2022-05-06 14:30:00,45000,Red,19000,6,1
6,7,Great Deal - Perfect for City Driving,2022-05-07 08:00:00,35000,Blue,17000,7,2
7,8,Sporty Look - Luxury Experience,2022-05-08 10:45:00,25000,Black,24000,8,4
8,9,Elegant Style - Performance Redefined,2022-05-09 13:15:00,15000,White,21000,9,4
9,10,Budget Friendly - Compact and Efficient,2022-05-10 09:30:00,5000,Gray,16000,10,1

In [ ]:
import pandas as pd
from datetime import datetime

# Data dummy untuk tabel Bids
data = {
    'bid_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'bid_price': [15000, 16000, 17000, 18000, 19000, 20000, 21000, 22000, 23000, 24000],
    'bid_posted': [datetime(2022, 5, 1, 8, 30), datetime(2022, 5, 2, 10, 15), datetime(2022, 5, 3, 13, 45),
                   datetime(2022, 5, 4, 9, 20), datetime(2022, 5, 5, 11, 0), datetime(2022, 5, 6, 14, 30),
                   datetime(2022, 5, 7, 8, 0), datetime(2022, 5, 8, 10, 45), datetime(2022, 5, 9, 13, 15),
                   datetime(2022, 5, 10, 9, 30)],
    'ads_id': [1, 2, 3, 5, 6, 1, 2, 4, 4, 1],
    'user_id': [11, 12, 14, 14, 15, 15, 16, 18, 29, 20]
}

# Membuat DataFrame dari data dummy
bids_df = pd.DataFrame(data)

# Menampilkan DataFrame
bids_df

   bid_id  bid_price          bid_posted  ads_id  user_id
0       1      15000 2022-05-01 08:30:00       1       11
1       2      16000 2022-05-02 10:15:00       2       12
2       3      17000 2022-05-03 13:45:00       3       14
3       4      18000 2022-05-04 09:20:00       5       14
4       5      19000 2022-05-05 11:00:00       6       15
5       6      20000 2022-05-06 14:30:00       1       15
6       7      21000 2022-05-07 08:00:00       2       16
7       8      22000 2022-05-08 10:45:00       4       18
8       9      23000 2022-05-09 13:15:00       4       29
9      10      24000 2022-05-10 09:30:00       1       20

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime

# Dummy data for Advertisement table
advertisement_data = {
    'ads_id': [1, 2, 3, 4, 5],
    'title': ['Excellent Condition', 'Great Deal', 'Sporty Look', 'Elegant Style', 'Budget Friendly'],
    'date_posted': ['2022-05-01', '2022-05-02', '2022-05-03', '2022-05-04', '2022-05-05'],
    'odometer': [50000, 40000, 30000, 20000, 10000],
    'color': ['Red', 'Blue', 'Black', 'White', 'Gray'],
    'price': [20000, 18000, 25000, 22000, 15000],
    'user_id': [101, 102, 103, 104, 105],
    'car_id': [201, 202, 203, 204, 205]
}

advertisement_df = pd.DataFrame(advertisement_data)

# Dummy data for Bids table
bids_data = {
    'bid_id': [1, 2, 3, 4, 5],
    'bid_price': [18000, 19000, 20000, 21000, 22000],
    'bid_posted': ['2022-05-01', '2022-05-02', '2022-05-03', '2022-05-04', '2022-05-05'],
    'ads_id': [1, 2, 3, 4, 5],
    'user_id': [201, 202, 203, 204, 205]
}

bids_df = pd.DataFrame(bids_data)

# # Joining Advertisement and Bids tables on ads_id
# merged_df = pd.merge(advertisement_df, bids_df, on='ads_id', how='inner')

# # Displaying the merged dataframe
# print("Merged DataFrame:")
# print(merged_df)

In [ ]:
advertisement_df

,ads_id,title,date_posted,odometer,color,price,user_id,car_id
0,1,Excellent Condition,2022-05-01,50000,Red,20000,101,201
1,2,Great Deal,2022-05-02,40000,Blue,18000,102,202
2,3,Sporty Look,2022-05-03,30000,Black,25000,103,203
3,4,Elegant Style,2022-05-04,20000,White,22000,104,204
4,5,Budget Friendly,2022-05-05,10000,Gray,15000,105,205

In [ ]:
bids_df

   bid_id  bid_price  bid_posted  ads_id  user_id
0       1      18000  2022-05-01       1      201
1       2      19000  2022-05-02       2      202
2       3      20000  2022-05-03       3      203
3       4      21000  2022-05-04       4      204
4       5      22000  2022-05-05       5      205

In [ ]:
# Joining Advertisement and Bids tables on ads_id
merged_df = pd.merge(advertisement_df, bids_df, on='ads_id', how='inner')

# Displaying the merged dataframe
print("Merged DataFrame:")
merged_df

Merged DataFrame:

,ads_id,title,date_posted,odometer,color,price,user_id_x,car_id,bid_id,bid_price,bid_posted,user_id_y
0,1,Excellent Condition,2022-05-01,50000,Red,20000,101,201,1,18000,2022-05-01,201
1,2,Great Deal,2022-05-02,40000,Blue,18000,102,202,2,19000,2022-05-02,202
2,3,Sporty Look,2022-05-03,30000,Black,25000,103,203,3,20000,2022-05-03,203
3,4,Elegant Style,2022-05-04,20000,White,22000,104,204,4,21000,2022-05-04,204
4,5,Budget Friendly,2022-05-05,10000,Gray,15000,105,205,5,22000,2022-05-05,205

In [ ]:
import pandas as pd
import numpy as np

# Dummy data for User_Data
user_data = pd.DataFrame({
    'user_id': range(1, 11),
    'first_name': ['John', 'Alice', 'Bob', 'Emma', 'Michael', 'Sarah', 'David', 'Olivia', 'James', 'Sophia'],
    'last_name': ['Doe', 'Smith', 'Johnson', 'Brown', 'Williams', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez'],
    'birth_date': pd.date_range(start='1980-01-01', end='1990-12-31', periods=10),
    'contact_num': np.random.randint(1000000000, 9999999999, size=10),
    'email': ['john.doe@example.com', 'alice.smith@example.com', 'bob.johnson@example.com',
              'emma.brown@example.com', 'michael.williams@example.com', 'sarah.jones@example.com',
              'david.garcia@example.com', 'olivia.miller@example.com', 'james.davis@example.com', 'sophia.rodriguez@example.com'],
    'address': ['123 Main St', '456 Elm St', '789 Oak St', '101 Pine St', '202 Maple St',
                '303 Cedar St', '404 Walnut St', '505 Cherry St', '606 Spruce St', '707 Pine St'],
    'city_id': np.random.randint(1, 6, size=10)  # Assuming 5 cities
})

# Dummy data for Advertisement
advertisement = pd.DataFrame({
    'ads_id': range(1, 11),
    'title': ['Car for Sale', 'Great Deal', 'Low Mileage', 'Excellent Condition', 'Affordable Price',
              'Luxury Car', 'Family Car', 'Sporty Model', 'City Drive', 'SUV for Sale'],
    'date_posted': pd.date_range(start='2022-05-01', end='2022-05-10', periods=10),
    'odometer': np.random.randint(10000, 100000, size=10),
    'color': ['Red', 'Blue', 'Black', 'White', 'Gray', 'Silver', 'Green', 'Yellow', 'Orange', 'Brown'],
    'price': np.random.randint(10000, 50000, size=10),
    'user_id': np.random.randint(1, 11, size=10),  # Assuming 10 users
    'car_id': np.random.randint(1, 11, size=10)  # Assuming 10 cars
})

# Dummy data for Bids
bids = pd.DataFrame({
    'bid_id': range(1, 11),
    'bid_price': np.random.randint(1000, 5000, size=10),
    'bid_posted': pd.date_range(start='2022-05-01', end='2022-05-10', periods=10),
    'user_id': np.random.randint(1, 11, size=10)  # Assuming 10 users
})

# Joining tables
joined_data = pd.merge(user_data, advertisement, on='user_id', suffixes=('_user', '_ad'))
joined_data = pd.merge(joined_data, bids, on='user_id')

joined_data

,user_id,first_name,last_name,birth_date,contact_num,email,address,city_id,ads_id,title,date_posted,odometer,color,price,car_id,bid_id,bid_price,bid_posted
0,3,Bob,Johnson,1982-06-11 16:00:00,8426729065,bob.johnson@example.com,789 Oak St,2,5,Affordable Price,2022-05-05,44590,Gray,33362,5,5,4862,2022-05-05
1,3,Bob,Johnson,1982-06-11 16:00:00,8426729065,bob.johnson@example.com,789 Oak St,2,5,Affordable Price,2022-05-05,44590,Gray,33362,5,6,4754,2022-05-06
2,3,Bob,Johnson,1982-06-11 16:00:00,8426729065,bob.johnson@example.com,789 Oak St,2,5,Affordable Price,2022-05-05,44590,Gray,33362,5,7,2744,2022-05-07
3,8,Olivia,Miller,1988-07-21 08:00:00,8214166948,olivia.miller@example.com,505 Cherry St,3,1,Car for Sale,2022-05-01,29725,Red,40079,4,3,3047,2022-05-03
4,9,James,Davis,1989-10-10 16:00:00,2081165068,james.davis@example.com,606 Spruce St,4,3,Low Mileage,2022-05-03,13925,Black,11061,7,2,3111,2022-05-02
5,9,James,Davis,1989-10-10 16:00:00,2081165068,james.davis@example.com,606 Spruce St,4,4,Excellent Condition,2022-05-04,56589,White,10288,7,2,3111,2022-05-02
6,9,James,Davis,1989-10-10 16:00:00,2081165068,james.davis@example.com,606 Spruce St,4,7,Family Car,2022-05-07,99704,Green,23257,10,2,3111,2022-05-02
7,9,James,Davis,1989-10-10 16:00:00,2081165068,james.davis@example.com,606 Spruce St,4,8,Sporty Model,2022-05-08,88830,Yellow,29174,10,2,3111,2022-05-02

In [ ]:
pip install faker

Collecting faker
  Downloading Faker-25.1.0-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 8.8 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-25.1.0

In [ ]:
import pandas as pd
import numpy as np
import random
from faker import Faker

# Inisialisasi objek Faker
fake = Faker(['id_ID'])

# Generate data dummy untuk user_data
data = {
    'user_id': range(1, 21),
    'first_name': [fake.first_name() for _ in range(20)],
    'last_name': [fake.last_name() for _ in range(20)],
    'birth_date': [fake.date_of_birth(minimum_age=18, maximum_age=90) for _ in range(20)],
    'contact_num': [fake.phone_number() for _ in range(20)],
    'email': [fake.email() for _ in range(20)],
    'address': [fake.address() for _ in range(20)],
    'city_id': [random.randint(1, 10) for _ in range(20)]  # Ganti 10 dengan jumlah kota yang ada dalam database Anda
}

# Membuat DataFrame
df_user_data = pd.DataFrame(data)

# Menampilkan DataFrame
df_user_data

,user_id,first_name,last_name,birth_date,contact_num,email,address,city_id
0,1,Tedi,Hasanah,1973-06-20,+62 (0753) 093-0335,caryani@example.com,"Jl. Sentot Alibasa No. 95\nTanjungpinang, Kali...",6
1,2,Maryanto,Yulianti,1943-06-20,0800222437,rmelani@example.org,"Gang Rumah Sakit No. 073\nTomohon, Banten 57195",9
2,3,Dian,Tampubolon,1973-06-22,+62 (040) 151 3094,nnashiruddin@example.org,"Gang Stasiun Wonokromo No. 33\nBinjai, Goronta...",4
3,4,Sadina,Waluyo,1953-09-06,+62-81-799-1566,taswirnajmudin@example.com,"Gg. Jend. A. Yani No. 06\nKupang, DI Yogyakart...",6
4,5,Marsudi,Najmudin,1962-01-07,081 814 2251,bakiadiwastuti@example.org,"Jl. Waringin No. 14\nSamarinda, Sumatera Selat...",9
5,6,Atmaja,Waskita,1953-11-21,+62 (648) 726-9587,cdamanik@example.com,"Jalan Rajawali Barat No. 49\nBima, YO 11723",9
6,7,Bakidin,Halim,1937-04-27,+62-322-751-1170,ksiregar@example.com,"Jalan Jend. A. Yani No. 986\nMalang, BE 58566",4
7,8,Estiono,Hutasoit,1964-04-10,+62 (035) 801 5632,budiyantofebi@example.net,"Gang Bangka Raya No. 3\nBinjai, Sulawesi Tenga...",3
8,9,Gaiman,Zulkarnain,1956-12-21,+62 (80) 547 6630,xanana15@example.net,"Gang Ahmad Dahlan No. 13\nDepok, Jawa Barat 26213",4
9,10,Gandi,Prasetya,1952-09-27,+62 (360) 047 7603,sitilailasari@example.net,"Jl. Tubagus Ismail No. 716\nTanjungbalai, MU 4...",7
10,11,Laras,Mardhiyah,1986-08-09,(0603) 021 4500,tsaragih@example.net,"Gg. Jamika No. 5\nBukittinggi, Riau 07118",9
11,12,Melinda,Usamah,1941-01-01,(0883) 256 1129,wulandarisarah@example.org,"Jl. Siliwangi No. 466\nMagelang, Sumatera Bara...",4
12,13,Ika,Hastuti,1949-12-23,+62 (31) 959 1341,natsirdirja@example.org,"Jalan Monginsidi No. 0\nPalopo, LA 56786",4
13,14,Lidya,Tamba,1993-06-06,+62 (90) 344-4953,wijayajais@example.com,"Gg. Gegerkalong Hilir No. 174\nDenpasar, Sumat...",6
14,15,Kemal,Najmudin,1983-10-29,+62 (958) 246 0340,febihardiansyah@example.org,Gang K.H. Wahid Hasyim No. 94\nKota Administra...,3
15,16,Farah,Nurdiyanti,1935-01-14,+62 (021) 658 1499,lestarirahmat@example.net,"Jl. Cikutra Timur No. 8\nTebingtinggi, SB 82014",5
16,17,Karen,Setiawan,1978-06-10,(074) 310 1130,sarah67@example.com,"Gang KH Amin Jasuta No. 34\nSukabumi, DKI Jaka...",10
17,18,Argono,Utama,1994-03-13,+62-092-109-4643,asmuni54@example.net,"Jl. S. Parman No. 760\nPalembang, Sulawesi Sel...",10
18,19,Hamzah,Maulana,2006-05-03,(010) 052-4212,rahmi93@example.com,"Gg. Astana Anyar No. 7\nBengkulu, DKI Jakarta ...",8
19,20,Tri,Haryanti,1947-10-17,+62 (92) 254-6289,shaniaprastuti@example.com,"Gg. M.T Haryono No. 8\nBanjarmasin, JI 76353",9

In [ ]:
import pandas as pd
import numpy as np
import random
from faker import Faker

# Buat data dummy untuk tabel bid_data
bid_data = {
    'bid_buyer_id': random.sample(range(1, 21), 8)  # Ambil 8 nilai acak dari user_id
}

# Buat DataFrame untuk bid_data
df_bid_data = pd.DataFrame(bid_data)

# Buat list dari user_id yang belum digunakan dalam bid_data
unused_user_ids = list(set(df_user_data['user_id']) - set(df_bid_data['bid_buyer_id']))

# Ambil 8 user_id yang belum digunakan
advertisement_user_ids = random.sample(unused_user_ids, 8)

# Buat data dummy untuk tabel advertisement_data
advertisement_data = {
    'ads_id': range(1, 9),
    'title': [fake.sentence(nb_words=6, variable_nb_words=True, ext_word_list=None) for _ in range(8)],
    'date_posted': [fake.date_time_this_month() for _ in range(8)],
    'odometer': [random.randint(10000, 50000) for _ in range(8)],
    'color': [fake.color_name() for _ in range(8)],
    'price': [random.randint(10000, 50000) for _ in range(8)],
    'user_id': advertisement_user_ids,
    'car_id': [random.randint(1, 10) for _ in range(8)]  # Ganti 10 dengan jumlah mobil yang ada dalam database Anda
}

# Buat DataFrame untuk advertisement_data
df_advertisement_data = pd.DataFrame(advertisement_data)

# Tampilkan DataFrame advertisement_data
df_advertisement_data

,ads_id,title,date_posted,odometer,color,price,user_id,car_id
0,1,Hic laborum quam cum similique sit ullam.,2024-05-01 02:37:38.916485,20278,Merah bata,14785,20,3
1,2,Sit mollitia ea.,2024-05-04 10:23:56.038157,40074,Magenta,11262,16,3
2,3,Placeat error ut occaecati id itaque eaque.,2024-05-07 12:24:19.127188,39208,Abu-abu,38852,6,9
3,4,Sint quos deserunt dolor.,2024-05-02 02:40:52.511236,22550,Coklat,33277,15,9
4,5,A at repellendus eius.,2024-05-03 20:34:56.555965,42962,Hitam,12580,5,2
5,6,Suscipit aperiam maxime necessitatibus ullam.,2024-05-01 02:35:33.816882,26002,Hitam,35151,17,1
6,7,Pariatur totam suscipit necessitatibus dicta.,2024-05-02 03:21:08.463658,44877,Emas,28189,19,1
7,8,Qui occaecati amet repellat.,2024-05-01 12:09:18.017823,13946,Biru,37830,3,7

In [ ]:
import pandas as pd
import random
from faker import Faker

# Inisialisasi objek Faker
fake = Faker(['id_ID'])

# Generate data dummy untuk bid_data
num_rows = 5  # Ubah menjadi 8 baris
unique_ads_id = range(1, 6)  # Ubah menjadi 5 id iklan yang unik
unique_user_ids = range(1, 21)  # Ubah menjadi 20 id pengguna yang unik

data = {
    'bid_id': range(1, num_rows + 1),
    'bid_price': [random.randint(10000, 30000) for _ in range(num_rows)],
    'bid_posted': [fake.date_time_this_month() for _ in range(num_rows)],
    'ads_id': [random.choice(unique_ads_id) for _ in range(num_rows)],  # Gunakan 5 id iklan yang telah diinisialisasi
    'bid_buyer_id': random.sample(unique_user_ids, num_rows)  # Gunakan sample acak dari id pengguna yang unik
}

# Membuat DataFrame
df_bid_data = pd.DataFrame(data)

# Menampilkan DataFrame
df_bid_data

   bid_id  bid_price                 bid_posted  ads_id  bid_buyer_id
0       1      19265 2024-05-05 01:07:05.006957       3             5
1       2      20079 2024-05-03 15:40:09.506309       1            13
2       3      28739 2024-05-06 19:34:04.778652       3             7
3       4      29656 2024-05-05 17:42:35.991882       2             9
4       5      23089 2024-05-03 08:55:04.347336       4             8

In [ ]:
# Merge (full join) antara df_bid_data dan df_advertisement_data
merged_data = pd.merge(df_bid_data, df_advertisement_data, on='ads_id')

# Tampilkan hasil merge
merged_data

,bid_id,bid_price,bid_posted,ads_id,bid_buyer_id,title,date_posted,odometer,color,price,user_id,car_id
0,1,19265,2024-05-05 01:07:05.006957,3,5,Placeat error ut occaecati id itaque eaque.,2024-05-07 12:24:19.127188,39208,Abu-abu,38852,6,9
1,3,28739,2024-05-06 19:34:04.778652,3,7,Placeat error ut occaecati id itaque eaque.,2024-05-07 12:24:19.127188,39208,Abu-abu,38852,6,9
2,2,20079,2024-05-03 15:40:09.506309,1,13,Hic laborum quam cum similique sit ullam.,2024-05-01 02:37:38.916485,20278,Merah bata,14785,20,3
3,4,29656,2024-05-05 17:42:35.991882,2,9,Sit mollitia ea.,2024-05-04 10:23:56.038157,40074,Magenta,11262,16,3
4,5,23089,2024-05-03 08:55:04.347336,4,8,Sint quos deserunt dolor.,2024-05-02 02:40:52.511236,22550,Coklat,33277,15,9

In [ ]:
# Gabungkan tabel df_bid_data dengan df_user_data berdasarkan bid_buyer_id dan user_id
df_bid_user = pd.merge(df_bid_data, df_user_data, left_on='bid_buyer_id', right_on='user_id', how='inner')

# Tampilkan DataFrame yang telah digabung
df_bid_user

,bid_id,bid_price,bid_posted,ads_id,bid_buyer_id,user_id,first_name,last_name,birth_date,contact_num,email,address,city_id
0,1,19265,2024-05-05 01:07:05.006957,3,5,5,Marsudi,Najmudin,1962-01-07,081 814 2251,bakiadiwastuti@example.org,"Jl. Waringin No. 14\nSamarinda, Sumatera Selat...",9
1,2,20079,2024-05-03 15:40:09.506309,1,13,13,Ika,Hastuti,1949-12-23,+62 (31) 959 1341,natsirdirja@example.org,"Jalan Monginsidi No. 0\nPalopo, LA 56786",4
2,3,28739,2024-05-06 19:34:04.778652,3,7,7,Bakidin,Halim,1937-04-27,+62-322-751-1170,ksiregar@example.com,"Jalan Jend. A. Yani No. 986\nMalang, BE 58566",4
3,4,29656,2024-05-05 17:42:35.991882,2,9,9,Gaiman,Zulkarnain,1956-12-21,+62 (80) 547 6630,xanana15@example.net,"Gang Ahmad Dahlan No. 13\nDepok, Jawa Barat 26213",4
4,5,23089,2024-05-03 08:55:04.347336,4,8,8,Estiono,Hutasoit,1964-04-10,+62 (035) 801 5632,budiyantofebi@example.net,"Gang Bangka Raya No. 3\nBinjai, Sulawesi Tenga...",3

In [ ]:
# Gabungkan tabel df_bid_user dengan df_advertisement_data berdasarkan ads_id
df_bid_user_advertisement = pd.merge(df_bid_data, df_advertisement_data, on='ads_id', how='outer')

# Tampilkan DataFrame yang telah d|igabung
df_bid_user_advertisement

,bid_id,bid_price,bid_posted,ads_id,bid_buyer_id,title,date_posted,odometer,color,price,user_id,car_id
0,1.0,19265.0,2024-05-05 01:07:05.006957,3,5.0,Placeat error ut occaecati id itaque eaque.,2024-05-07 12:24:19.127188,39208,Abu-abu,38852,6,9
1,3.0,28739.0,2024-05-06 19:34:04.778652,3,7.0,Placeat error ut occaecati id itaque eaque.,2024-05-07 12:24:19.127188,39208,Abu-abu,38852,6,9
2,2.0,20079.0,2024-05-03 15:40:09.506309,1,13.0,Hic laborum quam cum similique sit ullam.,2024-05-01 02:37:38.916485,20278,Merah bata,14785,20,3
3,4.0,29656.0,2024-05-05 17:42:35.991882,2,9.0,Sit mollitia ea.,2024-05-04 10:23:56.038157,40074,Magenta,11262,16,3
4,5.0,23089.0,2024-05-03 08:55:04.347336,4,8.0,Sint quos deserunt dolor.,2024-05-02 02:40:52.511236,22550,Coklat,33277,15,9
5,NaN,NaN,NaT,5,NaN,A at repellendus eius.,2024-05-03 20:34:56.555965,42962,Hitam,12580,5,2
6,NaN,NaN,NaT,6,NaN,Suscipit aperiam maxime necessitatibus ullam.,2024-05-01 02:35:33.816882,26002,Hitam,35151,17,1
7,NaN,NaN,NaT,7,NaN,Pariatur totam suscipit necessitatibus dicta.,2024-05-02 03:21:08.463658,44877,Emas,28189,19,1
8,NaN,NaN,NaT,8,NaN,Qui occaecati amet repellat.,2024-05-01 12:09:18.017823,13946,Biru,37830,3,7

In [ ]:
pip install faker

Collecting faker
  Downloading Faker-25.1.0-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 8.0 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-25.1.0

In [ ]:
import pandas as pd
from faker import Faker

# Inisialisasi Faker
fake = Faker('id_ID')

# Generate dummy data
num_cities = 30
cities_data = []

# Set untuk memeriksa keunikan nama kota
unique_city_names = set()

while len(cities_data) < num_cities:
    city_name = fake.city()
    if city_name not in unique_city_names:
        latitude = fake.latitude()
        longitude = fake.longitude()
        cities_data.append({
            'city_name': city_name,
            'latitude': latitude,
            'longitude': longitude
        })
        unique_city_names.add(city_name)

# Buat DataFrame dari data dummy
cities_df = pd.DataFrame(cities_data)
cities_df['city_id'] = range(1, num_cities + 1)

# Tambahkan city_id sebagai Primary Key
cities_df.set_index('city_id', inplace=True)

# Tampilkan DataFrame
cities_df

                                 city_name     latitude    longitude
city_id
1                              Tasikmalaya    34.923984    39.015309
2                                     Palu    76.100952   154.718732
3                                Palembang    47.456249  -120.422746
4                             Tebingtinggi  -69.7279525     1.793938
5                                    Batam   -68.401948   117.940224
6                                    Tegal   32.9278015   127.898433
7                                 Bengkulu  -89.7618875   -60.387273
8                             Tanjungbalai   -84.022860    79.055976
9                                Tangerang    71.200621    61.570684
10                                 Mataram   20.4686595   122.794874
11                               Surakarta   26.7058455    92.950682
12                              Sawahlunto   -9.6966905   128.483519
13                            Sungai Penuh    55.300784   -75.032565
14                        Padang Sidempuan   -51.946055  -150.645122
15                                Surabaya  -67.4122095  -164.955563
16                              Yogyakarta   52.8731125  -142.863453
17                                   Bogor   -25.876616   -47.260879
18       Kota Administrasi Jakarta Selatan    -0.152463   -52.226060
19                                Magelang  -54.1892865   -46.286644
20                                  Madiun   15.4562165    66.562275
21         Kota Administrasi Jakarta Pusat   78.5524325   -78.389312
22                                    Tual    35.318760  -121.500810
23                           Pangkalpinang  -52.7189715  -167.698493
24                             Banjarmasin   -24.098577   112.869997
25                                    Batu    78.656992    61.923843
26                              Balikpapan    40.127161   160.859941
27                             Lhokseumawe  -51.3811505   158.650833
28                                  Binjai   -76.183497     2.156770
29                            Lubuklinggau  -82.1554555   115.666244
30                               Pontianak   82.8228475  -171.541769

In [ ]:
# cities_df.to_csv('cities_df.csv', index=True)

In [ ]:
import pandas as pd
from faker import Faker
import random

# Inisialisasi Faker
fake = Faker('id_ID')

# Fungsi untuk generate email
def generate_email(first_name, last_name):
    return first_name.lower() + '.' + last_name.lower() + '@example.com'

# Generate dummy data
num_users = 200
users_data = []

# Ambil unique city_id dari cities_df
unique_city_ids = cities_df.index.tolist()

for i in range(num_users):
    # Generate unique first name and last name combination
    first_name = fake.first_name()
    last_name = fake.last_name()
    full_name = first_name + ' ' + last_name

    # Generate unique email
    email = generate_email(first_name, last_name)

    # Generate random city_id
    city_id = random.choice(unique_city_ids)

    # Generate random birth date
    birth_date = fake.date_of_birth(minimum_age=18, maximum_age=90)

    # Generate unique contact number
    contact_num = fake.phone_number()

    # Generate random address
    address = fake.street_address()

    users_data.append({
        'user_id': i + 1,
        'first_name': first_name,
        'last_name': last_name,
        'birth_date': birth_date,
        'contact_num': contact_num,
        'email': email,
        'address': address,
        'city_id': city_id
    })

# Buat DataFrame dari data dummy
users_df = pd.DataFrame(users_data)

# Tampilkan DataFrame
users_df

,user_id,first_name,last_name,birth_date,contact_num,email,address,city_id
0,1,Dinda,Haryanto,1982-06-30,+62 (085) 073 8648,dinda.haryanto@example.com,Jl. Jakarta No. 5,10
1,2,Cayadi,Suwarno,1940-08-21,(072) 889 4161,cayadi.suwarno@example.com,Jl. Kiaracondong No. 9,9
2,3,Rahayu,Wahyuni,1964-09-15,+62 (0737) 444-8598,rahayu.wahyuni@example.com,Gg. Otto Iskandardinata No. 8,13
3,4,Ivan,Adriansyah,1941-12-29,+62 (071) 386 8143,ivan.adriansyah@example.com,Jalan Kapten Muslihat No. 2,28
4,5,Yulia,Suryono,1995-12-02,+62 (054) 098 2222,yulia.suryono@example.com,Gg. Peta No. 8,4
...,...,...,...,...,...,...,...,...
195,196,Kusuma,Rahmawati,1972-09-25,+62 (758) 386 2914,kusuma.rahmawati@example.com,Jalan Sukabumi No. 43,10
196,197,Kartika,Novitasari,1996-10-06,+62-087-763-2645,kartika.novitasari@example.com,Jl. Cempaka No. 4,25
197,198,Garda,Megantara,1933-07-18,+62 (073) 839-3809,garda.megantara@example.com,Jalan Jakarta No. 982,30
198,199,Nasab,Aryani,1991-09-18,0808189500,nasab.aryani@example.com,Jalan H.J Maemunah No. 57,6
199,200,Mahdi,Novitasari,2003-02-26,+62 (028) 098 6865,mahdi.novitasari@example.com,Jalan Peta No. 62,12

In [ ]:
users_df.to_csv('users_df.csv', index=False)

In [ ]:
import pandas as pd
import random

# Generate unique car_id
car_ids = [i + 1 for i in range(20)]

# Generate 20 different car brands
car_brands = ['Toyota', 'Honda', 'Nissan', 'Mitsubishi', 'Suzuki',
              'Ford', 'Chevrolet', 'Hyundai', 'Kia', 'BMW',
              'Mercedes-Benz', 'Audi', 'Lexus', 'Volvo', 'Volkswagen',
              'Ferrari', 'Lamborghini', 'Porsche', 'Tesla', 'Jaguar']

# Generate 20 different car models
car_models = ['Corolla', 'Civic', 'Altima', 'Outlander', 'Swift',
              'Fiesta', 'Cruze', 'Elantra', 'Optima', '3 Series',
              'E-Class', 'A4', 'RX', 'S60', 'Golf', '488 GTB',
              'Aventador', '911', 'Model S', 'F-Type']

# Generate 20 different car types
car_types = ['Sedan', 'Hatchback', 'SUV', 'MPV', 'Coupe',
             'Convertible', 'Pickup', 'Van', 'Wagon', 'Crossover',
             'Luxury', 'Sport', 'Compact', 'Electric', 'Hybrid',
             'Minivan', 'Truck', 'Roadster', 'Supercar', 'Limousine']

# Generate random car transmission types (True or False)
car_transmissions = [random.choice([True, False]) for _ in range(20)]

# Generate random car years from 1980 to 2021
car_years = [random.randint(1980, 2021) for _ in range(20)]

# Create dictionary for dummy data
cars_data = {
    'car_id': car_ids,
    'car_brand': car_brands,
    'car_model': car_models,
    'car_type': car_types,
    'car_transmission': car_transmissions,
    'year': car_years
}

# Create DataFrame from dummy data
cars_df = pd.DataFrame(cars_data)

# Tampilkan DataFrame
cars_df

    car_id      car_brand  car_model     car_type  car_transmission  year
0        1         Toyota    Corolla        Sedan              True  1993
1        2          Honda      Civic    Hatchback             False  2008
2        3         Nissan     Altima          SUV             False  2011
3        4     Mitsubishi  Outlander          MPV              True  1980
4        5         Suzuki      Swift        Coupe             False  1980
5        6           Ford     Fiesta  Convertible             False  1994
6        7      Chevrolet      Cruze       Pickup             False  2017
7        8        Hyundai    Elantra          Van             False  2015
8        9            Kia     Optima        Wagon              True  2010
9       10            BMW   3 Series    Crossover             False  1987
10      11  Mercedes-Benz    E-Class       Luxury              True  1989
11      12           Audi         A4        Sport              True  1982
12      13          Lexus         RX      Compact             False  2018
13      14          Volvo        S60     Electric             False  2020
14      15     Volkswagen       Golf       Hybrid              True  1985
15      16        Ferrari    488 GTB      Minivan             False  2003
16      17    Lamborghini  Aventador        Truck             False  1998
17      18        Porsche        911     Roadster              True  1981
18      19          Tesla    Model S     Supercar             False  2003
19      20         Jaguar     F-Type    Limousine              True  1985

In [ ]:
# cars_df.to_csv('cars_df.csv', index=False)

In [ ]:
import pandas as pd
import random
from faker import Faker
import datetime

# Generate unique ads_id
ads_ids = [i + 1 for i in range(126)]

# Generate short descriptions for ads
fake = Faker('id_ID')
titles = [fake.sentence(nb_words=6) for _ in range(126)]

# Generate random date_posted
start_date = datetime.datetime(2023, 1, 1)
end_date = datetime.datetime.now()
date_posted = [fake.date_time_between(start_date=start_date, end_date=end_date) for _ in range(126)]

# Generate random odometer values
odometer = [random.randint(100, 100000) for _ in range(126)]

# Generate random colors for ads
colors = ['Black', 'White', 'Silver', 'Red', 'Blue', 'Gray', 'Green', 'Yellow', 'Orange',
          'Purple', 'Brown', 'Gold', 'Pink', 'Beige', 'Turquoise', 'Maroon', 'Navy']
color = [random.choice(colors) for _ in range(126)]

# Generate random prices for ads
price = [random.randint(100000000, 150000000) for _ in range(126)]

# Generate random user_ids from users_df
user_ids = random.choices(users_df['user_id'], k=126)

# Generate random car_ids from cars_df
car_ids = random.choices(cars_df['car_id'], k=126)

# Create dictionary for dummy data
ads_data = {
    'ads_id': ads_ids,
    'title': titles,
    'date_posted': date_posted,
    'odometer': odometer,
    'color': color,
    'price': price,
    'user_id': user_ids,
    'car_id': car_ids
}

# Create DataFrame from dummy data
ads_df = pd.DataFrame(ads_data)

# Tampilkan DataFrame
ads_df

,ads_id,title,date_posted,odometer,color,price,user_id,car_id
0,1,Eius aliquid repudiandae expedita.,2023-08-08 18:29:47.504270,56260,Pink,145173906,168,6
1,2,A necessitatibus suscipit ipsum quia tenetur.,2023-10-09 02:22:31.505148,12506,Maroon,118284858,67,13
2,3,Modi voluptatibus labore quo harum optio quam ...,2024-05-13 01:44:08.203883,29779,Blue,100379172,46,4
3,4,Voluptas dolores harum ipsa unde.,2023-12-17 00:15:25.921579,6766,Red,142330347,66,5
4,5,Quia odit velit explicabo placeat corrupti.,2023-07-14 22:18:07.120546,68493,Navy,109519696,72,9
...,...,...,...,...,...,...,...,...
121,122,Ab exercitationem repellat pariatur sequi.,2023-09-05 19:45:38.846729,85841,Navy,105041424,147,1
122,123,Minus aliquam nisi odit dolore voluptates quis...,2023-05-01 13:21:46.872456,136,Navy,118780521,174,19
123,124,Consequatur repudiandae placeat ex explicabo d...,2023-12-07 12:18:42.929514,12868,Turquoise,104206436,169,18
124,125,Expedita minima aut.,2024-05-12 05:12:01.536995,81288,Red,142669281,147,10
125,126,Iste ipsum alias ullam cum.,2023-12-28 01:09:58.886575,98464,Gray,106874157,132,16

In [ ]:
# Mengelompokkan data berdasarkan user_id dan menghitung jumlah ads_id untuk setiap kelompok
ads_count_by_user = ads_df.groupby('user_id')['ads_id'].count()

# Mendapatkan indeks dari baris dengan jumlah terbanyak untuk setiap kelompok (user_id)
max_ads_index_by_user = ads_count_by_user.idxmax()

# Mengambil ads_id dari baris dengan jumlah terbanyak untuk setiap kelompok (user_id)
max_ads_id_by_user = ads_df.loc[ads_df['user_id'] == max_ads_index_by_user, 'ads_id'].values[0]

print("ads_id dengan jumlah terbanyak untuk user_id", max_ads_index_by_user, "adalah", max_ads_id_by_user)

ads_id dengan jumlah terbanyak untuk user_id 179 adalah 81

In [ ]:
ads_df.to_csv('ads_df.csv', index=False)

In [ ]:
ads_df['user_id'].unique()

array([ 39, 107,  98, 183,  48, 139,  16,  19, 193, 192, 159,  40,  73,
       161,  56,  30, 133, 163,   6, 111,   5, 143, 166, 189, 136,  12,
       127,  99,  52,  88, 129, 199, 154,  45, 174,  75,   4,  90, 137,
       175, 113, 135,  79, 138, 130,  36,  54,  81,  76, 145,  46, 184,
        87, 156, 155,  68,  71, 144, 178, 104,  55, 112, 105, 103, 126,
        22,  23,  37,  84,  85, 177, 195,  24, 102, 170,  13, 117,  77,
        91, 123, 198, 153, 125,  70,   8,  60, 176,  66])

In [ ]:
import pandas as pd
import random
from faker import Faker
import datetime

# Generate unique bid_id
bid_ids = [i + 1 for i in range(80)]

# Generate random bid prices
bid_prices = [random.randint(80000000, 99000000) for _ in range(80)]

# Generate random bid_posted dates
start_date = datetime.datetime(2023, 1, 1)
end_date = datetime.datetime.now()
bid_posted = [fake.date_time_between(start_date=start_date, end_date=end_date) for _ in range(80)]

# Generate random ads_id from ads_df
ads_id = random.choices(ads_df['ads_id'], k=80)

# Generate random bid_buyer_id from users_df
bid_buyer_id = random.choices(users_df['user_id'], k=80)

# Create dictionary for dummy data
bids_data = {
    'bid_id': bid_ids,
    'bid_price': bid_prices,
    'bid_posted': bid_posted,
    'ads_id': ads_id,
    'bid_buyer_id': bid_buyer_id
}

# Create DataFrame from dummy data
bids_df = pd.DataFrame(bids_data)

# Tampilkan DataFrame
bids_df

    bid_id  bid_price                 bid_posted  ads_id  bid_buyer_id
0        1   80631417 2023-07-02 00:52:17.374861      19           178
1        2   86279121 2024-04-20 11:14:24.743547     118           111
2        3   97855787 2024-01-15 16:38:23.887724      40            17
3        4   82219906 2023-09-08 13:02:28.962263      96            20
4        5   84318652 2023-12-28 17:14:30.619697      32           144
..     ...        ...                        ...     ...           ...
75      76   93111664 2023-06-30 12:44:25.747501      18            13
76      77   88918233 2023-02-08 11:04:09.351123     122           194
77      78   95185934 2023-11-28 11:04:36.714353      87            13
78      79   91144836 2023-02-24 11:45:02.545939      85           177
79      80   80312603 2024-01-07 17:52:16.043091       1            20

[80 rows x 5 columns]

In [ ]:
bids_df.to_csv('bids_df.csv', index=False)

In [ ]:
# Joining ads_df and bids_df on ads_id
merged_df = pd.merge(ads_df, bids_df, on='ads_id', how='inner')

# Tampilkan DataFrame hasil join
merged_df

,ads_id,title,date_posted,odometer,color,price,user_id,car_id,bid_id,bid_price,bid_posted,bid_buyer_id
0,2,Dolore nobis at qui.,2023-03-01 03:11:51.352221,47114,Blue,121169879,184,6,8,91496791,2023-04-29 04:29:38.502385,30
1,3,Beatae magnam quos fugit qui error.,2023-01-18 00:42:05.676792,8080,Navy,141859801,71,20,52,86825664,2024-04-20 14:10:19.744450,87
2,3,Beatae magnam quos fugit qui error.,2023-01-18 00:42:05.676792,8080,Navy,141859801,71,20,53,86236528,2023-08-30 20:53:11.855573,20
3,7,Laudantium alias deleniti ducimus beatae dolor...,2023-09-13 03:45:20.652976,49935,Orange,100352469,84,14,3,97100503,2023-12-29 21:06:50.617995,47
4,9,Explicabo ipsum impedit molestias explicabo se...,2023-08-17 12:30:01.174330,63222,Purple,109333213,176,8,56,88429300,2023-03-29 03:50:49.315885,144
...,...,...,...,...,...,...,...,...,...,...,...,...
75,121,Soluta atque odio neque tempora cumque adipisc...,2023-12-06 09:44:28.479114,95196,Blue,134147641,101,19,78,85421923,2023-02-12 21:49:25.687102,75
76,123,Totam distinctio atque facilis voluptas.,2024-03-19 10:22:10.533664,79359,Maroon,117745781,155,17,28,86368368,2023-12-15 19:11:20.536346,195
77,123,Totam distinctio atque facilis voluptas.,2024-03-19 10:22:10.533664,79359,Maroon,117745781,155,17,60,93081890,2024-01-18 02:16:24.299206,52
78,123,Totam distinctio atque facilis voluptas.,2024-03-19 10:22:10.533664,79359,Maroon,117745781,155,17,76,92981273,2023-08-28 07:26:46.433719,149
79,125,Ea perferendis atque aperiam suscipit repudian...,2023-04-27 09:15:22.281173,85236,Orange,103639286,143,7,80,87560263,2024-03-13 17:57:01.607347,26